#ifndef DIO_Cfg_H
#define DIO_Cfg_H

#define DIO_DIR_INPUT 0
#define DIO_DIR_OUTPUT 1

#define DIO_INPUT_PULLUP 0
#define DIO_INPUT_PULLDOWN 1



typedef struct{
	u8 DIO_PinDirection;
	u8 DIO_InputStatus;
}DIO_tstrPinCfg_t;


const DIO_tstrPinCfg_t DIO_strPinCfg[32]= {
	/*Pin0*/{DIO_DIR_INPUT,DIO_INPUT_PULLUP},
	/*Pin1*/{DIO_DIR_INPUT,DIO_INPUT_PULLUP},
	/*Pin2*/{DIO_DIR_INPUT,DIO_INPUT_PULLUP},
	/*Pin3*/{DIO_DIR_INPUT,DIO_INPUT_PULLUP},
	/*Pin4*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin5*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin6*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin7*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin8*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin9*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin10*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN}, //PB2
	/*Pin11*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN}, //PB3
	/*Pin12*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin13*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin14*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin15*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin16*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin17*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin18*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin19*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin20*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin21*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin22*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin23*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN}, //PC7
	/*Pin24*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin25*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin26*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN}, //PD2
	/*Pin27*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN}, //PD3
	/*Pin28*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},
	/*Pin29*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN},//PD5
	/*Pin30*/{DIO_DIR_INPUT,DIO_INPUT_PULLUP}, //PD6
	/*Pin31*/{DIO_DIR_OUTPUT,DIO_INPUT_PULLDOWN}
	
	};

#endif /*DIO_Cfg_H*/